version: "3.6"
services:

  # https://hub.docker.com/r/_/postgres/
  db:
    # replace username/repo:tag with your name and image details
    image: mysql
    ports:
      # This image includes EXPOSE 5432 (the postgres port), so standard container linking will make it automatically available to the linked containers.
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: daw_grupo_7
      MYSQL_DATABASE: daw
      MYSQL_USER: daw
      MYSQL_PASSWORD: daw_grupo_7
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: {}